---
version: "4.0.28"
changelog:
  -
    changes:
      -
        text: "Added Concurrent-ruby gem."
        type: bugfix
    date: 14-05-2017
    version: "4.0.28"
  -
    changes:
      -
        text: "Fixed telemetry issues."
        type: bugfix
    date: 17-11-2017
    version: "4.0.27"
  -
    changes:
      -
        text: "Secured telemetry call. Fixed crash when an app was exiting."
        type: bugfix
    date: 23-10-2017
    version: "4.0.26"
  -
    changes:
      -
        text: "Added telemetry"
        type: feature
    date: 12-09-2017
    version: "4.0.25"
  -
    changes:
      -
        text: "Added #delete_messages method"
        type: feature
      -
        text: "Improved timeout error handling (thanks @f1sherman)"
        type: improvement
    date: 29-08-2017
    version: "4.0.24"
  -
    changes:
      -
        text: "Fixed HereNow envelope generation"
        type: bug
    date: 26-07-2017
    version: "4.0.23"
  -
    changes: 
      - 
        text: "Fixed signature generation and channel name escaping"
        type: bug
    date: 31-05-2017
    version: "4.0.22"
  - 
    changes: 
      - 
        text: "Fixed signature generation"
        type: bug
    date: 18-04-2017
    version: "4.0.21"
  - 
    changes: 
      - 
        text: "origin can now be set in initialized client"
        type: improvement
      - 
        text: "presence interval support"
        type: improvement
      - 
        text: "allows using multiple cipher keys"
        type: improvement
    date: 11-04-2017
    version: "4.0.20"
  - 
    changes: 
      - 
        text: "Fixed sync subscribe not terminating actors"
        type: bug
    date: 02-03-2017
    version: v4.0.18
  - 
    changes: 
      - 
        text: "Added a bit more debug logging"
        type: improvement
      - 
        text: "Updated default origin"
        type: improvement
    date: 21-12-2016
    version: v4.0.17
  - 
    changes: 
      - 
        text: "Fixed missing channel group parameter in leave event"
        type: bug
    date: ~
    version: v4.0.16
  - 
    changes: 
      - 
        text: "Fixed PAM signature when some special characters are present"
        type: bug
    date: ~
    version: v4.0.15
  - 
    changes: 
      - 
        text: "Added ttl parameter for publish"
        type: improvement
    date: ~
    version: v4.0.14
  - 
    changes: 
      - 
        text: "Changed init message log level to debug"
        type: improvement
    date: ~
    version: v4.0.13
  - 
    changes: 
      - 
        text: "Added alert on catchup failure (REQUEST_MESSAGE_COUNT_EXCEEDED)"
        type: improvement
    date: ~
    version: v4.0.12
  - 
    changes: 
      - 
        text: "Added super admin mode (Enabled when secret key is set on Pubnub::Client init)"
        type: improvement
    date: ~
    version: v4.0.11
  - 
    changes: 
      - 
        text: "Better single events timeout handling"
        type: improvement
      - 
        text: "DRYed envelope formatting a bit"
        type: improvement
    date: ~
    version: v4.0.10
  - 
    changes: 
      - 
        text: "Removed json dependency"
        type: improvement
      - 
        text: "Updated dependecies"
        type: improvement
    date: ~
    version: v4.0.9
  - 
    changes: 
      - 
        text: "Updated dry-validation."
        type: improvement
      - 
        text: "Dropped support for ruby 2.0."
        type: improvement
    date: ~
    version: v4.0.8
  - 
    changes: 
      - 
        text: "Added message decrypting in history."
        type: improvement
    date: ~
    version: v4.0.7
  - 
    changes: 
      - 
        text: "channel and channels are the same argument."
        type: improvement
      - 
        text: "channel_group and channel_groups are the same argument."
        type: improvement
      - 
        text: "added `with_presence` flag for subscribe, default false."
        type: improvement
    date: ~
    version: v4.0.6
  - 
    changes: 
      - 
        text: "Required CGI."
        type: improvement
    version: v4.0.5
  - 
    changes: 
      - 
        text: Added
        type: feature
    version: v4.0.2
  - 
    changes: 
      - 
        text: "Updated dry-validation and EnvelopeSchema."
        type: improvement
    version: v4.0.1
  - 
    changes: 
      - 
        text: "Removed auth_key and uuid setters (#set_auth_key,"
        type: feature
      - 
        text: Added
        type: improvement
    version: v4.0.0
  - 
    changes: 
      - 
        text: "Restored auth_key and uuid setters. Important notice: they will be removed"
        type: improvement
    version: v3.8.3
  - 
    changes: 
      - 
        text: "Added :include_token parameter to history call."
        type: feature
    version: v3.8.2
  - 
    changes: 
      - 
        text: "Updated celluloid dependency."
        type: improvement
    version: v3.8.1
  - 
    changes: 
      - 
        text: "Release of celluloid version of pubnub gem. It's complete rewrite but public API doesn't change."
        type: improvement
    version: v3.8.0
features: 
  access: 
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups: 
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  notify: 
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  presence: 
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish: 
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-SYNC
    - PUBLISH-ASYNC
    - PUBLISH-MESSAGE-TTL
  storage: 
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-DELETE-MESSAGES
  subscribe: 
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
  time: 
    - TIME-TIME
name: ruby
schema: 1
scm: github.com/pubnub/ruby
supported-platforms: 
  - 
    editors: 
      - "ruby 2.4.0"
      - "ruby 2.3.3"
      - "ruby 2.2.6"
      - "ruby 2.1.10"
      - jruby-9.1.8.0
    platforms: 
      - "FreeBSD 8-STABLE or later, amd64, 386."
      - "Linux 2.6 or later, amd64, 386."
      - "Mac OS X 10.8 or later, amd64"
      - "Windows 7 or later, amd64, 386, use rubyinstaller and dev pack."
      - "Apart from the above, PubNub Ruby SDK works on mostly all platforms where the supported Ruby versions work. To use ssl connection, Ruby should be compiled with openssl support."
    version: "PubNub Ruby SDK"
